Practica04BasicMVCWebApp/Models/ErrorViewModel.cs
using System;

namespace Practica04BasicMVCWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Practica04BasicMVCWebApp/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Practica04BasicMVCWebApp.Models
{
    public class Persona
    {

        public string Nombre { get; set; }
        public int Edad { get; set; }
    }
}

Practica04BasicMVCWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Practica04BasicMVCWebApp.Models;

namespace Practica04BasicMVCWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public string TestPage()
        {
            return "Saludo!";
        }

        public IActionResult TestPage2()
        {
            ViewData["Mensaje"] = "Página que utiliza una vista sin modelo";
            return View();
        }

        public IActionResult TestPage3()
        {
            
            Persona Karina = new Persona
            {
                Nombre = "Karina Rguez",
                Edad = 20
            };

            return View(Karina);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Practica04BasicMVCWebApp/Controllers/RecetarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Practica04BasicMVCWebApp.Controllers
{
    public class RecetarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Practica04BasicMVCWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Practica04BasicMVCWebApp/Views/Home/TestPage2.cshtml
@{
    ViewData["Title"] = "TestPage2";
}

<h1>TestPage2</h1>
<p>@ViewData["Mensaje"]</p>

Practica04BasicMVCWebApp/Views/Home/TestPage3.cshtml
@model Persona
@{
    ViewData["Title"] = "TestPage3";
}

<h1>TestPage3</h1>
<h2>Nombre: @Model.Nombre</h2>
<h3>Edad: @Model.Edad</h3>

Practica04BasicMVCWebApp/Views/Recetario/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Mariscos</h1>
        
            <!--<a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>-->
       
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">

        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="~/imagenes/cazuela.jpg" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">
                            En una caserola gruesa con tapa se coloca la bolsa o paquete de mariscos mixtos a cocinar hasta que queden lo suficientemente blandos, 
                            cuando hayan ablandado bien y se les haya secado un poco el agua se les coloca una lata de crema de ajo,
                            cortada en cuadritos, sal al gusto y se deja por espacio de 10 a 15 minutos.
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="~/imagenes/rissoto.jpg" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">Saltear los mariscos en el aceite con ajo, agregar en el sartén  el polvo de camarón, perejil seco, albahaca seca y pimienta. 
                        Añadir vino blanco al sartén, y esperar a que se concentre un poco. Reservar en un plato los camarones y mejillones.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="~/imagenes/pozole.jpg" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">
                            Esta es la misma receta que la receta tradicional del pozole rojo de Jalisco, pero con mariscos en lugar de carne de cerdo.
                            Se licuan los chiles guajillo y pasilla con el agua en que se hidrataron, junto con la sal, el orégano, la cebolla, el ajo y la pimienta negra.
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="~/imagenes/sopa.jpg" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">
                            Pele los camarones ya cocidos (cocer hasta que cambien su color y sacar inmediatalmente para que no se sobrecocinen y endurezcan) y quíteles la vena posterior. Limpie los filetes de piel y espinas, y córtelos en tiritas.
                            Cueza los fideos en agua salada hirviendo, hasta que estén suaves y escúrralos.
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top"src="~/imagenes/tostada.jpg" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">Comenzamos por poner los mariscos,  no importa el orden, encima continuamos con el pepino, cebolla y jitomate y algunas hojitas de cilantro, aquí viene una parte interesante de esta receta, es momento de agregar el chiltepín, 
                        mucho cuidado, porque recuerda que es muy picoso,  también la pimienta, la sal de grano, continuamos agregando el limón.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="~/imagenes/aguachile.jpg" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">
                            Cortar la cebolla blanca, el pepino, uno de los mangos, los tallos de cilantro y meterlos a la licuadora. Licuarlos con el jugo de limon. Reservar.
                            Pelar y limpiar los camarones. cortarlos en trozos.
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top"src="~/imagenes/clamw.jpeg" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">
                            Lo primero que haremos será limpiar correctamente las almejas. Para ello las sumergiremos en agua y una cantidad abundante de sal. De esta manera soltarán la arena y la suciedad que pudieran tener.
                            Debes dejarlas así al menos 30 minutos y si es posible, enjuagando y cambiando el agua una o dos veces, según lo limpias que estén.
                            Pica muy finamente la cebolla, el tocino y las papas en daditos de 1 cm cúbico, aproximadamente. Todos los ingredientes deben ser, más o menos, del mismo tamaño.
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="~/imagenes/almejas.jpg" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">
                            Lavar muy bien las almejas y cocerlas previamente.
                            Cortar el chorizo en cubos y cocinar en un sartén junto con una parte del vino blanco, removiendo continuamente.
                            Integrar la cebolla, el ajo y pimiento amarillo. Sofreír hasta que se acitrone la cebolla.
                            Sazonar rociando las semillas de comino, sal y cilantro. Agregar el resto del vino.
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="~/imagenes/cerveza.jpg" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">
                            Limpias bien los camarones, dejando la cola o al gusto. Los cortas por en medio y los reservas en un refractario.
                            Picas finamente el ajo y los echalotes y agregas a los camarones.
                            Agregas la cerveza y el aceite de oliva. Sazonas con sal y pimienta al gusto.
                            Mezclas muy bien y reservas por 20 minutos.
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Practica04BasicMVCWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practica04BasicMVCWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practica04BasicMVCWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recetario" asp-action="Index">Recetario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Practica04BasicMVCWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>